### ISSUE TITLE
No module named 'exoplasim.pyfft'

### ISSUE THREAD

**Issue by brianthomas-washburn** [alphaparrot/ExoPlaSim#13]
I saw this is in the known bugs in the Wiki area, hoping there is a simple fix.

I'm on Mint 21.3, using Python 3.10.12.

Using the exoplasim_tutorial.ipynb, everything appears to set up fine and starts running but then fails at the postprocess stage with the error:  No module named 'exoplasim.pyfft'

**Comment by brianthomas-washburn** [comment]
So I was able to fix this and get the model running (have run a couple of the test cases successfully).

I'm not certain exactly what the problem was, but I think it had to do with the f2py compile.  

Here's what I did:
1. Manually ran the "configure.sh" script in the python3.10/site-packages/exoplasim/ directory
    This succeeded but then when I went to run the model I got an error regarding versions of scipy and numpy.
2. I then uninstalled my scipy and numpy versions (pip uninstall ...) and reinstalled (pip install ...)

I think running the configure script fixed the f2py compile issue (for some reason) and the scipy/numpy verion issue was probably a separate thing.

I hope this helps someone else!

**Comment by robmod** [comment]
Hi @brianthomas-washburn. I'm encountering what seems to be the same error, however running configure.sh didn't seem to fix it. Is there anything you might have left out regarding what you did to fix this? Crossing my fingers, because right now I'm not sure what else to do. Thanks!

**Comment by alphaparrot** [comment]
I'm closing this since @brianthomas-washburn seems to have fixed the problem, and @robmod opened a separate issue with more detailed logs

**Comment by brianthomas-washburn** [comment]
Sorry for the lack of details on my solution.  Bad practice, but I pretty much just fiddled around until something worked.  Good lesson to keep better records!

**Comment by robmod** [comment]
@brianthomas-washburn No worries. I'll figure something out. Thanks.
