### ISSUE TITLE
Compatibility issues with new versions of libraries

### ISSUE THREAD

**Issue by alphaparrot** [alphaparrot/ExoPlaSim#24]
Compatibility issues noted with newer library versions:

- f2py2 no longer exists
- f2py argument order is stricter; `pyfft` must follow `-m`
- f2py build should be transitioned to meson
- some issues noted passing python versions>3.9 to the configuration script
- OpenMPI 5.0+ implements the MPI 4 standard which forbids function and variable names that start with `mpi_`. The PlaSim core is not compliant with MPI 4 and needs to be updated. Until this is done, only openmpi<5.0 will work.

**Comment by alphaparrot** [comment]
As of 9abf8cd most of these should be solved; will continue testing tonight and then try to release a maintenance update

**Comment by benjisimone** [comment]
What NumPy version would you recommend us?
I think that exoplasim installs by default the lastest version. In this case it installed 1.24.4 and I try to install 1.22.4, but it appeared incompatibilities with scipy and other modules. It may be related with the issue that you describe with Numpy's new version.
If you can give us the versions of the modules that you use would be very useful, so we can use them too.

**Comment by alphaparrot** [comment]
I believe the last stable version was compiled against either 1.21 or 1.22,
but yes, you're right that on new systems, this will cause problems for
scipy. The most recent version in the github repository should work with
the latest versions of NumPy, scipy, gcc, and OpenMPI 5.0.0 and lower
(5.0.1 and later have a bug in the conda-forge feedstock that prevents
compilation). The current code looks fairly stable so far, but there is
additional testing to be done before issuing a stable maintenance release.
The changes in the current version should address all the trouble we've had
with f2py and NumPy.
