### ISSUE TITLE
About google colab

### ISSUE THREAD

**Issue by alkis05** [alphaparrot/ExoPlaSim#25]
I understand that running mpi code is not recommended, but I would like to run it in google colab. Is there a way to pass the allow as root flag to mpirun in the config? 
If not, wouldn't it be worth it so people can run it in much better hardware than we have at home. Otherwise I can only use single core in google colab.

Its not like I will brake google if I run mpi as root on colab...

Also, I'm not certain it is related, but from my experience, at least in google colab we gotta pass the --oversubscribe flag to mpirun as well, or it complains that there are not enough slots availables.
If that is the case, it would be another reason to be able to pass flags to mpirun, if that is at all possible

**Comment by alphaparrot** [comment]
As of a few days ago, the latest version in this repository has an mpi_opts
keyword argument in the Model() constructor that will allow you to do
this—just pass in any arguments you need as a string, e.g.
"--allow-run-as-root --oversubscribe".

This will be fully documented and available on the pip version with the
next release.
