### ISSUE TITLE
ExoPlaSim crashing on virign Linux Mint system. Something to do with the file libmpi_usempif08.so.40 not being accessible.

### ISSUE THREAD

**Issue by CatoConroy** [alphaparrot/ExoPlaSim#30]
ExoPlaSim is crashing and claiming that a shared library file libmpi_usempif08.so.40 is non-accessible/doesn't exist. File Explorer is able to find the file. Crash also claims that plasim_restart and runtimes.log do not exist, supposedly due to the libmpi_usempif08.so.40 issue. Below is a screenshot of the terminal log as well as a screenshot depicting the file in file explorer. Any help would greatly be appreciated. Posting this here in-case anyone else has come across this problem.

![Screenshot from 2024-06-27 17-15-56](https://github.com/alphaparrot/ExoPlaSim/assets/88071894/4912bf3e-51ae-4c57-829f-28c99ff3a4ac)
![image](https://github.com/alphaparrot/ExoPlaSim/assets/88071894/17c70cde-7865-485b-86bd-ecabdae4f9c8)

**Comment by alphaparrot** [comment]
Closing as this was due to problems with user's installation procedure and was resolved by rebuilding conda environment and libraries
