### ISSUE TITLE
Configure script fails with Python version >= 3.10

### ISSUE THREAD

**Issue by zoqaeski** [alphaparrot/ExoPlaSim#9]
The Python version checking in `__init__.py` starting around line 76 fails when the installed Python version is newer than 3.10, because it trims the version number to three characters.

My system has Python 3.11 installed, and when running the initial configure script, it crashes trying to run Python 3.1, which doesn't exist.

**Comment by alphaparrot** [comment]
Version is now correctly passed through to configuration script, and also obviated by pivot to pythonic f2py compilation
